In [1]:
import pandas as pd

In [25]:
a=pd.read_csv('1000-1999.csv')

In [32]:
b=a.sample(n=200).reset_index(drop=True)
b['uid'].astype('str').tolist()

['6773605184',
 '2357028661',
 '5490055493',
 '6023963753',
 '5255493362',
 '3602903620',
 '6398065315',
 '2145049800',
 '6275819248',
 '6555947355',
 '6338835958',
 '6492567335',
 '5940209630',
 '5118878402',
 '6375469199',
 '6671504773',
 '5616791753',
 '3807599049',
 '5576066611',
 '6117668779',
 '5465795324',
 '6065409690',
 '1449924283',
 '6368218879',
 '2161482974',
 '2780805464',
 '2302320033',
 '6100860090',
 '5822139787',
 '5846440588',
 '3278435674',
 '6502479080',
 '6146027601',
 '6851954437',
 '6857794413',
 '6071237850',
 '6140558777',
 '5323768875',
 '6019444049',
 '2589971053',
 '6446035636',
 '6850443016',
 '1412958352',
 '2679554143',
 '5908263177',
 '5995660915',
 '1691717853',
 '2392867731',
 '2264466843',
 '5629984443',
 '5659708780',
 '6094440608',
 '2960905413',
 '6094489169',
 '3158444804',
 '3995440453',
 '6384992374',
 '5729098695',
 '3914163897',
 '1912369051',
 '2563072437',
 '5979169441',
 '6651047376',
 '5838714959',
 '5833397945',
 '5627518467',
 '5203839416',
 '6310927488',
 '6027070016',
 '2276959051',
 '5466950974',
 '3602429927',
 '5576416419',
 '2325694863',
 '6531729582',
 '5826246298',
 '5711520190',
 '6519778272',
 '5192239215',
 '6290021762',
 '6718190609',
 '3292828451',
 '6680817284',
 '5544861260',
 '6121854799',
 '5259604993',
 '6519077240',
 '6038420991',
 '6852028075',
 '1267628200',
 '5663092912',
 '5239084468',
 '6773397354',
 '1853492285',
 '5391297152',
 '6156939747',
 '6082414372',
 '6170334250',
 '5664650425',
 '3604424964',
 '5677075958',
 '5658939196',
 '6332180165',
 '6854563170',
 '6289941515',
 '2549307351',
 '5096701121',
 '1815742832',
 '6590665069',
 '3194426380',
 '6828021869',
 '2377491840',
 '5727539941',
 '1870319393',
 '1842626164',
 '6409374031',
 '5685924538',
 '2146327933',
 '6745404150',
 '6865329917',
 '5288668095',
 '2654719850',
 '6274629026',
 '6660001813',
 '6572058672',
 '6775137796',
 '5818734810',
 '1918313340',
 '3191585293',
 '1778594857',
 '6827360451',
 '6078149839',
 '6784925791',
 '6285938931',
 '2293638634',
 '6005639651',
 '6154357408',
 '6606126763',
 '5757099395',
 '5560665552',
 '6350099895',
 '6822854373',
 '6526226780',
 '6264964831',
 '2418238975',
 '5148673856',
 '6306993281',
 '5404027151',
 '5538696759',
 '6461841950',
 '6383839525',
 '5549087470',
 '6410527287',
 '2743649710',
 '6722234627',
 '2291269544',
 '1839343764',
 '1614704173',
 '5674772886',
 '1989006221',
 '5285002587',
 '6112975686',
 '6463185602',
 '5458518905',
 '3236693162',
 '2917791322',
 '6378943118',
 '6291072127',
 '5014218455',
 '3193449045',
 '6247577616',
 '5686825551',
 '5092835771',
 '5331585997',
 '5576382770',
 '6067890548',
 '6112576306',
 '6241820832',
 '2386707634',
 '6318363014',
 '6495730537',
 '2326690305',
 '2284689720',
 '5885626911',
 '6775146704',
 '2208091884',
 '5779222908',
 '6382182389',
 '5933070799',
 '6386078335',
 '1957779312',
 '1912428551',
 '3934498870',
 '6346652162',
 '1107687847',
 '6585615967',
 '5792244111',
 '6826467370',
 '6559162750',
 '5200312664']

In [10]:
b=a['sources'].mode().tolist()

In [11]:
b

['荣耀Magic2 魔法手机']

In [12]:
a

,attitudes,comments,have_pic,is_original,reposts,sources,texts,times
4,225095,203682,1,1,140863,荣耀Magic2 魔法手机,华硕灵耀U 2代\n全面屏笔记本\n看的更宽广\n美才更全面\n双11优惠来袭\n@华硕笔记...,1107
5,184996,104562,1,1,89906,荣耀Magic2 魔法手机,提前过双11，一起来玩石头剪刀布吧网页链接 #明星猜拳PK#，赢了我就送你专属福利哦~洁婷...,1105
6,199024,130410,1,1,144185,荣耀Magic2 魔法手机,#天猫双11#大家准备买什么呢？上特步官方旗舰店网页链接 解锁#特步特会玩#超值惊喜满满福利...,1101
7,292708,93710,0,0,419044,荣耀Magic2 魔法手机,你和我的倾城时光定档双十一！ 11月11日起每晚19:30 东方卫视✖浙江卫视黄金档 爱奇...,1026
8,232003,36561,0,1,120790,荣耀Magic2 魔法手机,谁说欧美才是时尚的前沿？国潮如今一样可以进驻英伦！今天，中国的厨电符号正以时尚的崭新姿态走进...,1025
9,650688,107953,1,1,282595,荣耀Magic2 魔法手机,最近网传、热心网友爆料、偶遇（偷拍）、P图，然后看图编故事，都可以变成新闻传播，辩驳一句也要...,1023
10,328151,41335,1,1,217429,荣耀Magic2 魔法手机,#我是荣耀Magic2头号玩家# 这是最近我收到的一个特别礼物，正面100%都是屏幕，也是我...,1022
11,7454403,2034000,1,1,5203997,荣耀10 AI变色更潮美,官宣,1016
12,1128539,301076,0,1,1316611,生日动态,祝你生日快乐,1016
13,185626,73336,0,0,102448,荣耀10 AI变色更潮美,阿雅姐用心做的节目，她说: 「看节目你会知道在世界的角落有很多人以各种各样的方式活着，自己眼...,1012

In [21]:
d1={'a1':[1],'b1':[2]}
d2={'c1':[3],'d1':[4]}
d3={}
d3.update(d1)
d3.update(d2)
d3

{'a1': [1], 'b1': [2], 'c1': [3], 'd1': [4]}

In [24]:
a['is_original'].count()

10

In [38]:
import numpy as np
a={'original_count': [0], 'have_pic_count': [0], 'total_weibo_count': [0], 'source': [], 'sum_attitudes': [0], 'sum_comments': [0], 'sum_reposts': [0], 'mean_attitudes': [0], 'mean_comments': [0], 'mean_reposts': [0]}
b={'name': ['家里蹲忙的跟狗似的2333'], 'uid': ['2098329887'], 'is_verified': ['False'], '关注人数': [194], 'fan_num': [29], 'gender': ['f'], 'level': [4]}
a.update(b)

In [42]:
a['original_count'][0]==0

True

In [46]:
c={'original_count': [0], 'have_pic_count': [0], 'total_weibo_count': [0], 'source': [np.nan], 'sum_attitudes': [0], 'sum_comments': [0], 'sum_reposts': [0], 'mean_attitudes': [0], 'mean_comments': [0], 'mean_reposts': [0], 'name': ['家里蹲忙的跟狗似的2333'], 'uid': ['2098329887'], 'is_verified': ['False'], '关注人数': [194], 'fan_num': [29], 'gender': ['f'], 'level': [4]}

In [47]:
c

{'original_count': [0],
 'have_pic_count': [0],
 'total_weibo_count': [0],
 'source': [nan],
 'sum_attitudes': [0],
 'sum_comments': [0],
 'sum_reposts': [0],
 'mean_attitudes': [0],
 'mean_comments': [0],
 'mean_reposts': [0],
 'name': ['家里蹲忙的跟狗似的2333'],
 'uid': ['2098329887'],
 'is_verified': ['False'],
 '关注人数': [194],
 'fan_num': [29],
 'gender': ['f'],
 'level': [4]}

In [48]:
pd.DataFrame(c)

,fan_num,gender,have_pic_count,is_verified,level,mean_attitudes,mean_comments,mean_reposts,name,original_count,source,sum_attitudes,sum_comments,sum_reposts,total_weibo_count,uid,关注人数
0,29,f,0,False,4,0,0,0,家里蹲忙的跟狗似的2333,0,NaN,0,0,0,0,2098329887,194

In [49]:
a=pd.read_csv('sample.csv')

In [50]:
a

,Unnamed: 0,fan_num,gender,have_pic_count,is_verified,level,mean_attitudes,mean_comments,mean_reposts,name,original_count,source,sum_attitudes,sum_comments,sum_reposts,total_weibo_count,uid,关注人数
0,0,31,f,0,False,4,0.000000,0.000000,0.0,平卉兆一威Davey,0,NaN,0,0,0,0,3980963837,53
1,1,80,m,1,False,14,0.000000,0.000000,0.0,人心丶29291,13,iPhone客户端,0,0,0,17,5537734126,453
2,2,1,f,0,False,1,0.000000,0.000000,0.0,用户6851935736,0,NaN,0,0,0,0,6851935736,22
3,3,91,f,19,False,14,1.842105,1.842105,0.0,我是小子涵,19,前置双摄vivo X9,35,35,0,19,5401367739,341
4,4,54,f,0,False,6,0.000000,0.000000,0.0,鹤归云间,0,NaN,0,0,0,0,6004847631,58
5,5,1,m,0,False,4,0.000000,0.000000,0.0,ss杰弟弟,0,NaN,0,0,0,0,6413929913,76
6,6,225,m,0,False,14,0.000000,0.000000,0.0,遞风o心,18,iPhone 6s Plus,0,0,0,26,3991116532,453
7,7,89,m,0,False,26,0.000000,0.000000,0.0,枯树生华,0,NaN,0,0,0,0,1760989205,303
8,8,41,f,0,False,9,0.000000,0.000000,0.0,鹿和羚,1,HUAWEI nova手机,0,0,0,2,5590205688,150
9,9,3,m,0,False,4,0.000000,0.000000,0.0,用户5990946509,0,NaN,0,0,0,0,5990946509,112
10,10,1,m,0,False,4,0.000000,0.000000,0.0,WSQ王思清,0,NaN,0,0,0,0,6738300259,22
11,11,191,f,0,False,31,0.000000,0.000000,0.0,再懒我就变成球er,2,iPhone客户端,0,0,0,8,2675687131,168
12,12,32,f,7,False,7,0.250000,0.833333,0.0,蓝色考拉Penelope,8,iPhone客户端,3,10,0,12,6129332816,67
13,13,51,m,0,False,4,0.000000,0.000000,0.0,假装今天吃过药了,0,NaN,0,0,0,0,6179699718,55
14,14,21,m,0,False,4,0.000000,0.000000,0.0,九凌QAQ,0,NaN,0,0,0,0,5853529939,131
15,15,851,f,0,False,21,0.000000,0.000000,0.0,poarla,0,NaN,0,0,0,0,2257357873,282
16,16,2,m,0,False,4,0.000000,0.000000,0.0,哇哈哈粉丝团,0,NaN,0,0,0,0,6283035756,2
17,17,16,f,0,False,8,0.000000,0.000000,0.0,pang耶,0,NaN,0,0,0,0,5371951883,184
18,18,61,m,0,False,4,0.000000,0.000000,0.0,地根天,0,NaN,0,0,0,0,5343064207,210
19,19,134,m,0,False,14,0.000000,0.000000,0.0,早睡的黑眼圈,0,NaN,0,0,0,0,2917791322,194

In [53]:
b=pd.read_csv('hjmd.csv')

In [58]:
c=b['Code'].astype('str').tolist()

In [59]:
len(c)

113

In [60]:
c[0:20]

['1266873830',
 '1338252410',
 '1380262714',
 '1550936751',
 '1580838020',
 '1595452017',
 '1627718624',
 '1682478870',
 '1685263893',
 '1687678704',
 '1694831243',
 '1737276191',
 '1737468690',
 '1740350792',
 '1751120234',
 '1769358757',
 '1781387383',
 '1787624284',
 '1794349680',
 '1796133687']

In [63]:
c[20:40]

['1799506375',
 '1806841204',
 '1807830442',
 '1826562655',
 '1842476903',
 '1846836925',
 '1849983497',
 '1856181753',
 '1864992092',
 '1865017937',
 '1878250733',
 '1878496465',
 '1888741665',
 '1897662683',
 '1921566117',
 '1938073311',
 '1945268717',
 '1946582314',
 '1952099555',
 '1960465721']

In [64]:
c[20:40,43:50]2436672594

TypeError: list indices must be integers or slices, not tuple

In [65]:
c[62]

'2436672594'

In [66]:
c[100:]

['5386777684',
 '5394557775',
 '5405993013',
 '5496961974',
 '5542799804',
 '5707739917',
 '5797537990',
 '5960726022',
 '6027001836',
 '6045629846',
 '6072469593',
 '6290636330',
 '6406649869']